# Generated by Django 5.1.1 on 2024-11-02 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_operator', '0002_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
