# Generated by Django 5.1.1 on 2024-11-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_operator', '0004_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(blank=True, null=True)),
                ('book_title', models.CharField(default='Unknown', max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='book_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='book_title',
        ),
    ]
