# Generated by Django 5.1.1 on 2024-11-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_operator', '0005_orderitemdata_remove_purchase_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
